### ISSUE TITLE
Extended the block to get results from the API using a Query term

### ISSUE THREAD

**Issue by vagelisp** [lenasterg/wp_ccsearch#8]
Hello 👋 
I would like some help regarding the licences we're querying and the query options we should give to the users.
Thanks.

related to #7

**Comment by lenasterg** [comment]
Hi. 
Currently, the Openverse API doesn't have an endpoint for the available licenses. So the plugin doesn't give the option for to user to select the license he/she wants. 

In the current version, the user can only limit the source of the images (from which provider he/she wants to get the image). 
The providers are given in a <select> box, next to the <input>.  
https://github.com/lenasterg/ls-wp-ccsearch/blob/7869e968e7eca7f15ee24e2da4ea490afeae0f73/index.php#L278 

The code which fills the Providers <select> box options, via the API is given in:

https://github.com/lenasterg/ls-wp-ccsearch/blob/7869e968e7eca7f15ee24e2da4ea490afeae0f73/assets/js/backend.js#L10-L25

 
Also, the function with the query used to fetch the results is given in: 

https://github.com/lenasterg/ls-wp-ccsearch/blob/7869e968e7eca7f15ee24e2da4ea490afeae0f73/index.php#L162

FYI: 

The idea for the licenses endpoint in the API is very good and I forwarded it to the Openverse team Slack channel. 
They currently have them hardcoded only in the Openverse site: https://github.com/WordPress/openverse-frontend/blob/main/src/constants/license.js

**Comment by vagelisp** [comment]
Hello, thanks for all the info.

I'll update the block's save function next week then we can chat about any block options you think we should have in the editor.

**Comment by vagelisp** [comment]
Closing because of #10
